apiVersion: v1
kind: Pod
metadata:
  name: appdocker-pod
  labels:
    app: webapp-db
spec:
  containers:
    - name: webapp
      image: appdocker:dev
      ports:
        - containerPort: 8080
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
      command: ["sh", "-c", "dotnet ef database update --project AppDocker && dotnet AppDocker.dll"]
    - name: postgres
      image: postgres:latest
      env:
        - name: POSTGRES_DB
          value: "db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 5432

# apiVersion: v1
# kind: Pod
# metadata:
#   name: appdocker-pod
# spec:
#   containers:
#     - name: webapp
#       image: appdocker:dev
#       ports:
#         - containerPort: 8080
#     - name: postgres
#       image: postgres:latest
#       env:
#         - name: POSTGRES_PASSWORD
#           value: "postgres"
#       ports:
#         - containerPort: 5432
#       volumeMounts:
#         - name: empty-volume
#           mountPath: /empty
#   volumes:
#     - name: empty-volume
#       emptyDir: {}
