apiVersion: v1
kind: Pod
metadata:
  name: appdocker-pod
  labels:
    app: webapp-db
spec:
  containers:
    - name: webapp
      image: kristinasilvanovych/appdockerps:dev
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: empty-volume
          mountPath: /empty-2 
    - name: postgres
      image: kristinasilvanovych/postgreswb
      env:
        - name: POSTGRES_DB
          value: "db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: empty-volume
          mountPath: /empty-1       
  volumes:
    - name: empty-volume
      emptyDir: {}
