version: '3.4'

networks: 
  dev: 
    driver: bridge

services:
  webapp:
    image: appdocker:dev
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - dev
    command: >
      sh -c "dotnet ef database update --project AppDocker" 
  
  database:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks: 
      - dev


volumes:
    pg_data:
        external: true