apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
spec:
  containers:
    - name: webapp
      image: kristinasilvanovych/webapp:dev
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /webapp-data
          name: hostpath-volume
  volumes:
    - name: hostpath-volume
      hostPath: 
        path: /data
        type: DirectoryOrCreate

